config/routes.rb
Freshimetrics::Application.routes.draw do
  

  devise_for :users
 

  resources :users
  resources :events


  get "welcome/home"
  get "welcome/about"
  root to: 'welcome#home'
  match 'events' => "events#index", via: :options

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :parameters 
  accepts_nested_attributes_for :parameters, :allow_destroy => true
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

  layout 'application'
  skip_before_action :verify_authenticity_token
  before_filter :cors_preflight_check 
  after_filter :cors_set_access_control_headers 
 
  #neccessary in all controllers that will respond with JSON
  respond_to :json

  #trying to set CORS response headers in controller actions
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*' 
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end


  #disabling the CSRF protection 
  private

  def permission_denied_error
   error(403, 'Permission Denied!')
  end

  def error(status, message = 'Something went wrong')
    response = {
    response_type: "ERROR",
    message: message
    }

    render json: response.to_json, status: status
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :verify_authentication_controller
  skip_before_action :verify_authenticity_token
  before_filter :cors_preflight_check 
  after_filter :cors_set_access_control_headers 
 
  #neccessary in all controllers that will respond with JSON
  respond_to :json

  #trying to set CORS response headers in controller actions
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*' 
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end


 
  # GET /events
  # GET /events.json
  def index
  end

  # POST /events
  # POST /events.json
  def create
    # app_owner = params['app_owner']
    # puts "*** #{params[app_owner]}"
    # puts "*** #{params['app_owner']}"
    # user = User.find_by_email(app_owner)
    # user.events.create!(event_params)

    # blocmetrics.track("some event name", {property_1: "some value", property_2: "some other value"})
    # {"name"=>"Page Views", "application"=>"Bloccit", "topic_name"=>"officiis enim laboriosam quibusdam aperiam qui voluptatum et iusto", "app_user"=>"4", "app_owner"=>"douglaswalter2@gmail.com", "event"=>{"name"=>"Page Views"}}
    Rails.logger.info(">>>>>>>>>This is in heroku")

    @event = Event.create(name: params[:name], property_1: params[:topic_name], property_2: params[:app_owner])
    Rails.logger.info ">>>>>> #{@event.inspect}"
    Rails.logger.info ">>>>> #{params.inspect}"
    respond_to do |format|
      format.json { head :ok }
      format.js
    end
  end


  private
  def permission_denied_error
   error(403, 'Permission Denied!')
  end

  def error(status, message = 'Something went wrong')
    response = {
    response_type: "ERROR",
    message: message
    }

    render json: response.to_json, status: status
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
    event = @events.first
    @application_name = event.application
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div>


    <h3> Event Data for Application: <%= @application_name %></h3>
    
    <div class="row">
      <div class="col-md-6">
        <h5 class="text-centered">Most Pages Viewed</h5>
        <%= pie_chart @events.group(:topic_name).count %>
      </div>

      <div class="col-md-6">
        <h5 class="text-centered">User Activity</h5>
        <%= column_chart @events.group(:app_user).count %>
        <small>* id-0 is non-user activity</small>
      </div>

      <div class="col-md-6">
        <h5 class="text-centered">Activity by Day</h5>
        <%= line_chart @events.group_by_day(:created_at).count %>
      </div>
    </div>

 

</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Event Data for Application: Bloccit</h1>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @event.body %>
</p>

<%# Attempting to implement Chart.js%>
<script src="Chart.js"> 
  <canvas id="myChart" width="400" height="400"> 

    var ctx = document.getElementById("myChart").getContext("2d");
    var myNewChart = new Chart(ctx).PolarArea(data);


    var ctx = $("#myChart").get(0).getContext("2d");

    var myNewChart = new Chart(ctx);

    new Chart(ctx).Line(data,opitons);

      var data = {
        labels : ["January","February","March","April","May","June","July"],
        datasets : [
        {
       fillColor : "rgba(220,220,220,0.5)",
       strokeColor : "rgba(220,220,220,1)",
       pointColor : "rgba(220,220,220,1)",
       pointStrokeColor : "#fff",
       data : [65,59,90,81,56,55,40]
        },
      {
       fillColor : "rgba(151,187,205,0.5)",
       strokeColor : "rgba(151,187,205,1)",
       pointColor : "rgba(151,187,205,1)",
       pointStrokeColor : "#fff",
       data : [28,48,40,19,96,27,100]
      }
      ]
      }

  </canvas>
</script>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Freshimetrics" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"><%= link_to "Freshimetrics", root_path %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    
    <ul class="right">
     <li class="has-dropdown">
      <a href="#">Start Here!</a>
        <ul class="dropdown">
          <% if current_user %>
           <li><%= link_to('My Events', events_path) %></li>
           <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li><%= link_to("Sign In",new_user_session_path) %></li>
            <li><%= link_to("Sign Up",new_user_registration_path) %></li>
          <% end %>            
        </ul>
      </li>
    </ul>
  
  </section>
  </nav>

 

 <%= yield %>




    <%= javascript_include_tag "application" %>
    <%= yield :page_scripts %>
  </body>
  
</html>

app/views/layouts/orbit.html.erb
 <div class="orbit-container">
  <ul data-orbit class="example-orbit orbit-slides-container>
    <li>
      <img src="http://i1261.photobucket.com/albums/ii591/fresh5447/3bddf8b2-786e-4133-8820-64fd063cc48b_zpseff0643c.jpg" alt="slide 1" />
      <div class="orbit-caption">
        Should be Ninja?.
      </div>
    </li>
    <li class="active">
      <img src="http://i1261.photobucket.com/albums/ii591/fresh5447/Contact_zps6ddfa92d.jpg" alt="slide 2" />
      <div class="orbit-caption">
        Not sure what this is
      </div>
    </li>
    <li>
      <img src="http://i1261.photobucket.com/albums/ii591/fresh5447/Thanks_zps531c8ef7.jpg" alt="slide 3" />
      <div class="orbit-caption">
        This should be Thank you?
      </div>
    </li>
  </ul>

  <!-- Navigation Arrows -->
  <a href="#" class="orbit-prev">Prev <span></span></a>
  <a href="#" class="orbit-next">Next <span></span></a>

  <!-- Slide Numbers -->
  <div class="orbit-slide-number">
    <span>1</span> of <span>3</span>
  </div>

  <!-- Timer and Play/Pause Button -->
  <div class="orbit-timer">
    <span></span>
    <div class="orbit-progress"></div>
  </div>
</div>

<!-- Bullets -->
<ol class="orbit-bullets">
  <li data-orbit-slide-number="1"></li>
  <li data-orbit-slide-number="2" class="active"></li>
  <li data-orbit-slide-number="3"></li>
</ol>



    <div class="row">
      <div class="small-8 columns"><%= yield %></div>
      <div class="small-4 columns" >
        <h2>About Us</h2>
        An analytical plugin used to track the success of your web application.
      </div>
    </div>

app/views/welcome/about.html.erb
<h1> This is the about page? Where is it showing..</h1>

<% content_for :page_scripts do %>
  <script> 

  $(function(){ 
      // track a client-side event using the Blocmetrics analytics service
    var _bm_event = {
      name: "Page Views",
      application: "Bloccit",
      topic_name: "Some topic",
      app_user: "<%= current_user ? current_user.id : 0 %>", // --> where 0 represents non-user activity
      app_owner: "douglaswalter2@gmail.com" // admin, general email to synch app with Blocmetrics view for app_owner  
    }

    var _bm_request = new XMLHttpRequest();
    _bm_request.open("POST", "http://localhost:3000/events", true);
    _bm_request.setRequestHeader('Content-Type', 'application/json');
    _bm_request.onreadystatechange = function() {
      // this function runs when the Ajax request changes state.
      // https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
     
    };
    _bm_request.send(JSON.stringify(_bm_event));
  }());

  </script>
<% end %>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Freshimetrics" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

   
  <div class="large-9 medium-8 columns">
    <h1> This is a custom web annalytics app.</h1>
      <h2 class="subheader"> 
        <ul>
          <li>Custom Metrics to track anything you desire!</li> 
          <li>30 day free trial</li>
          <li>Starting at $5 a month</li>
        </ul>
      </h2>
      
  </div>




    <%= javascript_include_tag "application" %>
  </body>
  
</html>